### ISSUE TITLE
Switch out nvim-lsp-installer for mason.nvim

### ISSUE THREAD

**Issue by arafatamim** [junnplus/nvim-lsp-setup#20]
The author of nvim-lsp-installer [decided to deprecate](https://github.com/williamboman/nvim-lsp-installer#ℹ%EF%B8%8F-project-status) the project and introduce [mason.nvim](https://github.com/williamboman/mason.nvim) as its successor. Looks like this plugin will have to be updated to accommodate this change.

**Comment by junnplus** [comment]
Thanks for reminding me, I will take some time to migrate it.

**Comment by travisby** [comment]
Thanks for this fix!
