### ISSUE TITLE
LSP broken

### ISSUE THREAD

**Issue by l3aro** [junnplus/nvim-lsp-setup#9]
* neovim: 0.7
* williamboman/nvim-lsp-installer: [latest commit](https://github.com/williamboman/nvim-lsp-installer/commit/cd4dac02a3bb5431979b0812a80dadf6ee088f5e)

Install on new machine, or run update plugin on old machine will make LSP malfunction. It seems the problem come from the [last commit](https://github.com/junnplus/nvim-lsp-setup/commit/3afa053f624284f4db9c73e497c3ecd602e2444f). If I checkout the the previous commit then reload editor, everything is good again

**Comment by junnplus** [comment]
Can you provide error messages or reproducible configs?

**Comment by l3aro** [comment]
After you remind that `reproducible config`, I take a look at your new comit and my setup, then see your new `require('lspconfig')[server_name].setup(config)` conflicts with my setup of `nvim-cmp`
Thanks again for your nice plugin!
Issue close.
